[package]
name = "wikibook_kujira"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


# ch2 
[dependencies]
rand = "0.8.0"

# ch3

[[example]]
name = "e1_maze"
path = "ch2/e1_maze.rs"